global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /certs/dynamic_conf.yml
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: "example@gmail.com"
      storage: "/acme.json"
      tlsChallenge: {}

